modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/fnuecke/oc2r/issues"
license = "MIT"

[[mods]]
modId = "oc2r"
version = "${file.jarVersion}"
displayName = "OpenComputers II: Reimagined"
authors = "North Western Development (Originally by Sangar)"
description = '''
Modern computers for the modern player.

This mod uses the Terminus Font under the Open Font License. The full license can be found in the JAR of this mod.
'''

[[dependencies.oc2r]]
modId = "forge"
mandatory = true
versionRange = "[40.1.68,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.oc2r]]
modId = "minecraft"
mandatory = true
versionRange = "1.20.1"
ordering = "NONE"
side = "BOTH"
[[dependencies.oc2r]]
modId = "sedna"
mandatory = true
versionRange = "[1.0.14,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.oc2r]]
modId = "markdown_manual"
mandatory = true
versionRange = "[1.2.1,)"
side = "CLIENT"
